export const assets = {
  homeMeeting: "/images/mc-home-atuacao-integrada.webp",
  officeMateriality: "/images/mc-escritorio-materialidade.webp",
  homeHero: "/images/mc-home-hero-desktop.webp",
  homeHeroMobile: "/images/mc-home-hero-mobile.webp",
  homeIpLayers: "/images/mc-home-ip-camadas.webp",
  homeDecisions: "/images/mc-home-decisoes-estrategicas.webp",
  officeHero: "/images/mc-escritorio-hero-desktop.webp",
  officeHeroMobile: "/images/mc-escritorio-hero-mobile.webp",
  officeTeam: "/images/mc-escritorio-multidisciplinar.webp",
  professionalsTeam: "/images/mc-profissionais-equipe-desktop.webp",
  areasHero: "/images/mc-areas-hero-sistema.webp",
  contactDesktop: "/images/mc-contato-sao-paulo-desktop.webp",
  contactMobile: "/images/mc-contato-sao-paulo-mobile.webp",
  texture: "/images/mc-textura-mineral-tile.webp",
  openGraph: "/images/mc-og-base.webp",
} as const;

export const suppliedAssetNames = [
  "1cbded9f-65b1-438b-b6a9-e97b48367d72.png",
  "c-escritorio-materialidade.webp",
  "mc-area-contencioso-arbitragem.webp",
  "mc-area-contratos.webp",
  "mc-area-propriedade-intelectual.webp",
  "mc-areas-hero-sistema.webp",
  "mc-area-societario-ma.webp",
  "mc-area-tecnologia-dados.webp",
  "mc-area-trabalhista-empresarial.webp",
  "mc-area-tributario.webp",
  "mc-contato-sao-paulo-mobile.webp",
  "mc-contato-sao-paulo-desktop.webp.png",
  "mc-escritorio-hero-desktop.webp",
  "mc-escritorio-hero-mobile.webp",
  "mc-escritorio-multidisciplinar.webp",
  "mc-home-decisoes-estrategicas.webp",
  "mc-home-hero-desktop.webp",
  "mc-home-hero-mobile.webp",
  "mc-home-ip-camadas.webp",
  "mc-insight-arbitragem-negociacao.webp",
  "mc-insight-estrategia-marcas.webp",
  "mc-insight-ia-direitos-autorais.webp",
  "mc-insight-trabalho-inovacao.webp",
  "mc-og-base.webp",
  "mc-profissional-01.webp",
  "mc-profissional-02.webp",
  "mc-profissional-03.webp",
  "mc-profissional-04.webp",
  "mc-profissional-05.webp",
  "mc-profissional-06.webp",
  "mc-profissionais-equipe-desktop.webp.png",
  "mc-textura-mineral-tile.webp",
] as const;
