export const assets = {
  logoHorizontalColor: "/brand/mc-logo-horizontal-color.svg",
  logoHorizontalWhite: "/brand/mc-logo-horizontal-white.svg",
  logoSymbolColor: "/brand/mc-logo-symbol-color.svg",
  homeMeeting: "/images/mc-home-atuacao-integrada.webp",
  officeMateriality: "/images/mc-escritorio-materialidade.webp",
  homeHero: "/images/mc-home-hero-desktop.webp",
  homeHeroMobile: "/images/mc-home-hero-mobile.webp",
  homeIpLayers: "/images/mc-home-ip-camadas.webp",
  homeDecisions: "/images/mc-home-decisoes-estrategicas.webp",
  officeHero: "/images/mc-escritorio-hero-desktop.webp",
  officeHeroMobile: "/images/mc-escritorio-hero-mobile.webp",
  officeTeam: "/images/mc-escritorio-multidisciplinar.webp",
  professionalsTeam: "/images/mc-profissionais-equipe-desktop.webp",
  areasHero: "/images/mc-areas-hero-sistema.webp",
  contactDesktop: "/images/mc-contato-sao-paulo-desktop.webp",
  contactMobile: "/images/mc-contato-sao-paulo-mobile.webp",
  texture: "/images/mc-textura-mineral-tile.webp",
  openGraph: "/images/mc-og-base.webp",
} as const;
